---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

    # Uncomment the following verifier to leverage Inspec instead of Busser (the
    # default verifier)
    # verifier:
    #   name: inspec

platforms:
  - name: centos
    run_list:
      - recipe[yum]
    driver_config:
      image: centos
      platform: rhel
  - name: ubuntu
    run_list:
      - recipe[apt]
    driver_config:
      image: ubuntu
      platform: debian

suites:
  - name: default
    run_list:
      - recipe[apache2]
      - recipe[apache2::mod_rewrite]
      - recipe[apache2::mod_expires]
      - recipe[apache2::mod_ssl]
      - recipe[omeka::default]
    attributes: 
      machine_fqdn: working.computers.biz
      machine_fqdn_as_hostname: true
      apache2:
        listen_ports: ["80", "443"]
