settings:
  parallel: true

driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    run_command: /sbin/init
    provision_command:
      - /usr/bin/yum install -y initscripts net-tools wget
- name: centos-7
  run_list:
    - recipe[yum]
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
    - /bin/yum install -y initscripts net-tools wget
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y


suites:
  - name: default
    run_list:
      #    - recipe[build-essential]
      - recipe[php::default]
      - recipe[apache2]
      - recipe[apache2::mod_rewrite]
        # - recipe[apache2::mod_expires]
      - recipe[apache2::mod_ssl]
      - recipe[apache2::mod_php5]
      - recipe[omeka::solo]
    attributes: 
      machine_fqdn: omeka.dev
      machine_fqdn_as_hostname: true
      apache2:
        #  listen_ports: ["80", "443"]
      omeka:
        plugins:
          list: [
  'Neatline-2.5.1.zip',
  'NeatlineFeatures-2.0.5.zip',
  'Neatline-Widget-SIMILE-Timeline-2.0.4.zip',
  'Neatline-Widget-Text-1.1.0.zip',
  'Neatline-Time-2.1.0.zip',
  'Neatline-Widget-Waypoints-2.0.2.zip',
  'UniversalViewer-2.2.zip',
  'IIIF-1.0.zip'
]
