---
driver:
  name: ec2
  require_chef_omnibus: true
  instance_type: t2.micro

transport:
  ssh_key: /home/atg/.ssh/id_rsa
  connection_timeout: 10
  connection_retries: 5

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-fce3c696

suites:
  - name: default
    run_list:
      #      - recipe[build-essential]
      - recipe[php::default]
      - recipe[apache2]
      - recipe[apache2::mod_rewrite]
        # - recipe[apache2::mod_expires]
      - recipe[apache2::mod_ssl]
      - recipe[apache2::mod_php5]
      - recipe[omeka::default]
      - recipe[omeka::solo]
    attributes: 
      machine_fqdn: omeka.dev
      machine_fqdn_as_hostname: true
      apache2:
        listen_ports: ["80", "443"]
      omeka:
        addons:
          plugins: [
              'Neatline-2.5.1.zip',
              'NeatlineFeatures-2.0.5.zip',
              'Neatline-Widget-SIMILE-Timeline-2.0.4.zip',
              'Neatline-Widget-Text-1.1.0.zip',
              'Neatline-Time-2.1.0.zip',
              'Neatline-Widget-Waypoints-2.0.2.zip',
              'UniversalViewer-2.2.zip',
              'IIIF-1.0.zip'
              ]
          themes: [
              'Berlin-2.3.1.zip'
              ]
