---
driver:
  name: ec2
  require_chef_omnibus: true
  instance_type: t2.micro

transport:
  ssh_key: /home/atg/.ssh/id_rsa
  connection_timeout: 10
  connection_retries: 5

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-fce3c696
  - name: amazon-linux
    driver:
      image_id: ami-8fcee4e5

suites:
  - name: default
    run_list:
      - recipe[build-essential]
      - recipe[php::default]
      - recipe[apache2]
      - recipe[apache2::mod_rewrite]
      - recipe[apache2::mod_expires]
      - recipe[apache2::mod_ssl]
      - recipe[apache2::mod_php5]
      - recipe[omeka::solo]
    attributes: 
      machine_fqdn: omeka.dev
      machine_fqdn_as_hostname: true
      apache2:
        listen_ports: ["80", "443"]
