---
driver:
  name: vagrant

provisioner:
  name: chef_zero

    # Uncomment the following verifier to leverage Inspec instead of Busser (the
    # default verifier)
    # verifier:
    #   name: inspec

platforms:
  - name: centos-7.0
    run_list:
    - recipe[yum]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[php::default]
      - recipe[apache2]
      - recipe[apache2::mod_rewrite]
      - recipe[apache2::mod_expires]
      - recipe[apache2::mod_ssl]
      - recipe[apache2::mod_php5]
      - recipe[omeka::default]
    attributes: 
      machine_fqdn: working.computers.biz
      machine_fqdn_as_hostname: true
      apache2:
        listen_ports: ["80", "443"]
