---
driver:
  name: ec2
  require_chef_omnibus: true
  instance_type: m3.medium
  availability_zone: us-east-1e

transport:
  ssh_key: /home/atg/.ssh/id_rsa
  connection_timeout: 10
  connection_retries: 5

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-b2e3c6d8
    transport:
      username: ubuntu
