---
driver:
  name: vagrant

provisioner:
  name: chef_zero

    # Uncomment the following verifier to leverage Inspec instead of Busser (the
    # default verifier)
    # verifier:
    #   name: inspec

platforms:
  - name: centos-7.0
    run_list:
      - recipe[yum]
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8081}]

suites:
  - name: default
    run_list:
      - recipe[php::default]
      - recipe[apache2]
      - recipe[apache2::mod_rewrite]
      - recipe[apache2::mod_ssl]
      - recipe[apache2::mod_php5]
      - recipe[omeka::default]
      - recipe[omeka::solo]
    attributes: 
      poise_debug: true
      machine_fqdn: omeka.dev
      machine_fqdn_as_hostname: true
      apache2:
        listen_ports: ["80", "443"]
      omeka:
        addons:
          plugins: [
              'Neatline-2.5.1.zip',
              'NeatlineFeatures-2.0.5.zip',
              'Neatline-Widget-SIMILE-Timeline-2.0.4.zip',
              'Neatline-Widget-Text-1.1.0.zip',
              'Neatline-Time-2.1.0.zip',
              'Neatline-Widget-Waypoints-2.0.2.zip',
              'UniversalViewer-2.2.zip',
              'IIIF-1.0.zip'
              ]
          themes: [
              'Berlin-2.3.1.zip'
              ]
