---
settings:
  parallel: true

driver:
  name: docker
  use_sudo: false
  privileged: true
  provision_command: &1
    - curl -L http://www.opscode.com/chef/install.sh | bash
  #remove_images: true

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    provision_command:
      - /usr/bin/yum install -y initscripts net-tools wget
- name: centos-7
  run_list:
    - recipe[yum]
  driver:
    image: centos:7
    platform: rhel
    provision_command:
    - /bin/yum install -y initscripts net-tools wget
<% %w(14.04 16.04).each do |ubver| %>
- name: ubuntu-<%= ubver %>
  driver:
    image: ubuntu:<%= ubver %>
    platform: ubuntu
<% end %>
