name 'omeka'
maintainer 'Harvard ATG'
maintainer_email 'josh_beauregard@harvard.edu'
license 'MIT License'
description 'A helper for a LAMP Stack running Omeka'
long_description 'A helper Stack for running the Omeka (http://omeka.org), software stack'
version '0.1.0'

depends 'yum', '~> 3.5.2'
depends 'ssh', '~> 0.10.10'
depends 'mysql', '~> 6.1.2'
depends 'nginx', '~> 2.7.6'
depends 'php', '~> 1.7.2'
depends 'zip', '~> 1.1.0'
